---
- name: Configure Airflow
  hosts: airflow
  become: yes
  tasks:
    - name: Install Python and pip
      apt:
        name:
          - podman
          - python3
          - python3-pip
        update_cache: yes
        state: present

    - name: Install Airflow 2.10.4 with pip
      pip:
        name: apache-airflow==2.10.4
        executable: pip3

    - name: Initialize Airflow DB
      command: airflow db init

    - name: Create admin user
      command: >
        airflow users create
        --username admin
        --password admin
        --firstname admin
        --lastname user
        --role Admin
        --email admin@tims.com

    - name: Start Airflow in background
      shell: nohup airflow standalone &> /tmp/airflow.log &
